[2022-12-10 16:27:18,966] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: mysql-to-gcp.inserting-data-into-bigquery 2022-12-10T16:04:47.638429+00:00 [queued]>
[2022-12-10 16:27:19,019] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: mysql-to-gcp.inserting-data-into-bigquery 2022-12-10T16:04:47.638429+00:00 [queued]>
[2022-12-10 16:27:19,020] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-12-10 16:27:19,021] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-12-10 16:27:19,022] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-12-10 16:27:19,051] {taskinstance.py:1063} INFO - Executing <Task(PythonVirtualenvOperator): inserting-data-into-bigquery> on 2022-12-10T16:04:47.638429+00:00
[2022-12-10 16:27:19,073] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'mysql-to-gcp', 'inserting-data-into-bigquery', '2022-12-10T16:04:47.638429+00:00', '--job-id', '14', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/gcp_dag.py', '--cfg-path', '/tmp/tmpep24l_aj', '--error-file', '/tmp/tmpcy8beam8']
[2022-12-10 16:27:19,061] {standard_task_runner.py:52} INFO - Started process 321 to run task
[2022-12-10 16:27:19,075] {standard_task_runner.py:77} INFO - Job 14: Subtask inserting-data-into-bigquery
[2022-12-10 16:27:19,328] {logging_mixin.py:104} INFO - Running <TaskInstance: mysql-to-gcp.inserting-data-into-bigquery 2022-12-10T16:04:47.638429+00:00 [running]> on host ec559b4d8f4f
[2022-12-10 16:27:19,535] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=mysql-to-gcp
AIRFLOW_CTX_TASK_ID=inserting-data-into-bigquery
AIRFLOW_CTX_EXECUTION_DATE=2022-12-10T16:04:47.638429+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-10T16:04:47.638429+00:00
[2022-12-10 16:27:19,538] {process_utils.py:135} INFO - Executing cmd: virtualenv /tmp/venv88uarkkq --system-site-packages
[2022-12-10 16:27:19,615] {process_utils.py:137} INFO - Output:
[2022-12-10 16:27:21,474] {process_utils.py:141} INFO - created virtual environment CPython3.6.15.final.0-64 in 954ms
[2022-12-10 16:27:21,476] {process_utils.py:141} INFO -   creator CPython3Posix(dest=/tmp/venv88uarkkq, clear=False, no_vcs_ignore=False, global=True)
[2022-12-10 16:27:21,477] {process_utils.py:141} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/airflow/.local/share/virtualenv)
[2022-12-10 16:27:21,479] {process_utils.py:141} INFO -     added seed packages: pip==21.0.1, setuptools==52.0.0, wheel==0.36.2
[2022-12-10 16:27:21,480] {process_utils.py:141} INFO -   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[2022-12-10 16:27:21,537] {process_utils.py:135} INFO - Executing cmd: /tmp/venv88uarkkq/bin/pip install google-cloud-bigquery google-cloud-bigquery-storage
[2022-12-10 16:27:21,552] {process_utils.py:137} INFO - Output:
[2022-12-10 16:27:26,731] {process_utils.py:141} INFO - Requirement already satisfied: google-cloud-bigquery in /home/airflow/.local/lib/python3.6/site-packages (2.8.0)
[2022-12-10 16:27:26,746] {process_utils.py:141} INFO - Requirement already satisfied: google-cloud-bigquery-storage in /home/airflow/.local/lib/python3.6/site-packages (2.2.1)
[2022-12-10 16:27:27,018] {process_utils.py:141} INFO - Requirement already satisfied: google-resumable-media<2.0dev,>=0.6.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery) (1.2.0)
[2022-12-10 16:27:27,025] {process_utils.py:141} INFO - Requirement already satisfied: google-cloud-core<2.0dev,>=1.4.1 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery) (1.6.0)
[2022-12-10 16:27:27,035] {process_utils.py:141} INFO - Requirement already satisfied: protobuf>=3.12.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery) (3.14.0)
[2022-12-10 16:27:27,042] {process_utils.py:141} INFO - Requirement already satisfied: google-api-core[grpc]<2.0.0dev,>=1.23.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery) (1.26.0)
[2022-12-10 16:27:27,047] {process_utils.py:141} INFO - Requirement already satisfied: proto-plus>=1.10.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery) (1.13.0)
[2022-12-10 16:27:27,154] {process_utils.py:141} INFO - Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (1.52.0)
[2022-12-10 16:27:27,163] {process_utils.py:141} INFO - Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (2.25.1)
[2022-12-10 16:27:27,173] {process_utils.py:141} INFO - Requirement already satisfied: google-auth<2.0dev,>=1.21.1 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (1.26.1)
[2022-12-10 16:27:27,176] {process_utils.py:141} INFO - Requirement already satisfied: setuptools>=40.3.0 in /tmp/venv88uarkkq/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (52.0.0)
[2022-12-10 16:27:27,182] {process_utils.py:141} INFO - Requirement already satisfied: packaging>=14.3 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (20.9)
[2022-12-10 16:27:27,187] {process_utils.py:141} INFO - Requirement already satisfied: pytz in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (2020.5)
[2022-12-10 16:27:27,194] {process_utils.py:141} INFO - Requirement already satisfied: six>=1.13.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (1.15.0)
[2022-12-10 16:27:27,202] {process_utils.py:141} INFO - Requirement already satisfied: grpcio<2.0dev,>=1.29.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (1.35.0)
[2022-12-10 16:27:27,287] {process_utils.py:141} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/airflow/.local/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (4.7)
[2022-12-10 16:27:27,291] {process_utils.py:141} INFO - Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (4.2.1)
[2022-12-10 16:27:27,296] {process_utils.py:141} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/airflow/.local/lib/python3.6/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (0.2.8)
[2022-12-10 16:27:27,363] {process_utils.py:141} INFO - Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery) (1.1.2)
[2022-12-10 16:27:27,378] {process_utils.py:141} INFO - Requirement already satisfied: cffi>=1.0.0 in /home/airflow/.local/lib/python3.6/site-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery) (1.14.5)
[2022-12-10 16:27:27,389] {process_utils.py:141} INFO - Requirement already satisfied: pycparser in /home/airflow/.local/lib/python3.6/site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery) (2.20)
[2022-12-10 16:27:27,443] {process_utils.py:141} INFO - Requirement already satisfied: pyparsing>=2.0.2 in /home/airflow/.local/lib/python3.6/site-packages (from packaging>=14.3->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (2.4.7)
[2022-12-10 16:27:27,481] {process_utils.py:141} INFO - Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/airflow/.local/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (0.4.8)
[2022-12-10 16:27:27,545] {process_utils.py:141} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/airflow/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (2020.12.5)
[2022-12-10 16:27:27,549] {process_utils.py:141} INFO - Requirement already satisfied: chardet<5,>=3.0.2 in /home/airflow/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (3.0.4)
[2022-12-10 16:27:27,554] {process_utils.py:141} INFO - Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/airflow/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (1.25.11)
[2022-12-10 16:27:27,556] {process_utils.py:141} INFO - Requirement already satisfied: idna<3,>=2.5 in /home/airflow/.local/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery) (2.10)
[2022-12-10 16:27:27,731] {process_utils.py:141} INFO - Requirement already satisfied: libcst>=0.2.5 in /home/airflow/.local/lib/python3.6/site-packages (from google-cloud-bigquery-storage) (0.3.17)
[2022-12-10 16:27:27,897] {process_utils.py:141} INFO - Requirement already satisfied: typing-inspect>=0.4.0 in /home/airflow/.local/lib/python3.6/site-packages (from libcst>=0.2.5->google-cloud-bigquery-storage) (0.6.0)
[2022-12-10 16:27:27,923] {process_utils.py:141} INFO - Requirement already satisfied: pyyaml>=5.2 in /home/airflow/.local/lib/python3.6/site-packages (from libcst>=0.2.5->google-cloud-bigquery-storage) (5.4.1)
[2022-12-10 16:27:27,980] {process_utils.py:141} INFO - Requirement already satisfied: dataclasses>=0.6.0 in /home/airflow/.local/lib/python3.6/site-packages (from libcst>=0.2.5->google-cloud-bigquery-storage) (0.7)
[2022-12-10 16:27:28,011] {process_utils.py:141} INFO - Requirement already satisfied: typing-extensions>=3.7.4.2 in /home/airflow/.local/lib/python3.6/site-packages (from libcst>=0.2.5->google-cloud-bigquery-storage) (3.7.4.3)
[2022-12-10 16:27:28,210] {process_utils.py:141} INFO - Requirement already satisfied: mypy-extensions>=0.3.0 in /home/airflow/.local/lib/python3.6/site-packages (from typing-inspect>=0.4.0->libcst>=0.2.5->google-cloud-bigquery-storage) (0.4.3)
[2022-12-10 16:27:55,759] {process_utils.py:141} INFO - WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
[2022-12-10 16:27:55,760] {process_utils.py:141} INFO - You should consider upgrading via the '/tmp/venv88uarkkq/bin/python -m pip install --upgrade pip' command.
[2022-12-10 16:27:55,981] {process_utils.py:135} INFO - Executing cmd: /tmp/venv88uarkkq/bin/python /tmp/venv88uarkkq/script.py /tmp/venv88uarkkq/script.in /tmp/venv88uarkkq/script.out /tmp/venv88uarkkq/string_args.txt
[2022-12-10 16:27:55,991] {process_utils.py:137} INFO - Output:
[2022-12-10 16:28:04,359] {process_utils.py:141} INFO - [[34m2022-12-10 16:28:04,358[0m] {[34mbase.py:[0m74} INFO[0m - Using connection to: id: mysql_default. Host: host.docker.internal, Port: 3306, Schema: classicmodels, Login: root, Password: XXXXXXXX, extra: None[0m
[2022-12-10 16:28:13,006] {process_utils.py:141} INFO - Traceback (most recent call last):
[2022-12-10 16:28:13,009] {process_utils.py:141} INFO -   File "/tmp/venv88uarkkq/script.py", line 87, in <module>
[2022-12-10 16:28:13,022] {process_utils.py:141} INFO -     pickle.dump(res, file)
[2022-12-10 16:28:13,027] {process_utils.py:141} INFO - AttributeError: Can't pickle local object 'if_exception_type.<locals>.if_exception_type_predicate'
[2022-12-10 16:28:13,856] {taskinstance.py:1455} ERROR - Command '['/tmp/venv88uarkkq/bin/python', '/tmp/venv88uarkkq/script.py', '/tmp/venv88uarkkq/script.in', '/tmp/venv88uarkkq/script.out', '/tmp/venv88uarkkq/string_args.txt']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 493, in execute
    super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 531, in execute_callable
    string_args_filename,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/process_utils.py", line 145, in execute_in_subprocess
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venv88uarkkq/bin/python', '/tmp/venv88uarkkq/script.py', '/tmp/venv88uarkkq/script.in', '/tmp/venv88uarkkq/script.out', '/tmp/venv88uarkkq/string_args.txt']' returned non-zero exit status 1.
[2022-12-10 16:28:13,862] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=mysql-to-gcp, task_id=inserting-data-into-bigquery, execution_date=20221210T160447, start_date=20221210T162718, end_date=20221210T162813
[2022-12-10 16:28:13,937] {local_task_job.py:146} INFO - Task exited with return code 1
